// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";


export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: "postgresql://" + env("POSTGRES_USER") + ":" + env("POSTGRES_PASSWORD") + "@localhost:" + env("DB_PORT") + "/" + env("POSTGRES_DB") + "?schema=public",
  },
});
